# permissions for end users to edit blobstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-bucket-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: blobstorage-editor-role
rules:
- apiGroups:
  - k8s.migueleliasweb.io
  resources:
  - blobstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.migueleliasweb.io
  resources:
  - blobstorages/status
  verbs:
  - get
